True
[0]
initialize network with normal
cuda:0
================ (Mon Apr  1 20:20:38 2024) ================
gpu_ids: [0] project_name: CD_STANet_LEVIR_b4_lr0.01_sgd_train_test_100_linear_ce checkpoint_root: /media/dsk2/zhongyu.zhang/project/ChangeFormer/checkpoints vis_root: /media/dsk2/zhongyu.zhang/project/ChangeFormer/vis num_workers: 2 dataset: CDDataset data_name: LEVIR batch_size: 4 split: train split_val: test img_size: 256 shuffle_AB: False n_class: 2 embed_dim: 64 pretrain: None multi_scale_train: False multi_scale_infer: False multi_pred_weights: [0.5, 0.5, 0.5, 0.8, 1.0] net_G: STANet loss: ce optimizer: sgd lr: 0.01 max_epochs: 100 lr_policy: linear lr_decay_iters: 100 checkpoint_dir: /media/dsk2/zhongyu.zhang/project/ChangeFormer/checkpoints/CD_STANet_LEVIR_b4_lr0.01_sgd_train_test_100_linear_ce vis_dir: /media/dsk2/zhongyu.zhang/project/ChangeFormer/vis/CD_STANet_LEVIR_b4_lr0.01_sgd_train_test_100_linear_ce 

training from scratch...


lr: 0.0100000
 
  0%|          | 0/1780 [00:00<?, ?it/s]  0%|          | 0/1780 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main_cd.py", line 91, in <module>
    train(args)
  File "main_cd.py", line 19, in train
    train_loss=model.train_models()
  File "/media/dsk2/zhongyu.zhang/project/ChangeFormer/models/trainer.py", line 334, in train_models
    self._forward_pass(batch)
  File "/media/dsk2/zhongyu.zhang/project/ChangeFormer/models/trainer.py", line 285, in _forward_pass
    self.G_pred = self.net_G(img_in1, img_in2)
  File "/media/dsk2/zhongyu.zhang/anaconda/envs/pyt36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/dsk2/zhongyu.zhang/project/ChangeFormer/models/STANet.py", line 309, in forward
    f1, f2 = self.attend(f1, f2)
  File "/media/dsk2/zhongyu.zhang/anaconda/envs/pyt36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/dsk2/zhongyu.zhang/project/ChangeFormer/models/STANet.py", line 295, in forward
    y = self.att(x)
  File "/media/dsk2/zhongyu.zhang/anaconda/envs/pyt36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/dsk2/zhongyu.zhang/project/ChangeFormer/models/STANet.py", line 200, in forward
    energy = torch.bmm(query, key)
RuntimeError: CUDA out of memory. Tried to allocate 16.00 GiB (GPU 0; 10.76 GiB total capacity; 1.60 GiB already allocated; 7.99 GiB free; 1.65 GiB reserved in total by PyTorch)
